#!/usr/bin/env bash
# hotinbeauty crawl 스케줄 (launchd) 설치 / 재로드 / 해제.
# usage:
#   scripts/install-mac-launchd.sh install
#   scripts/install-mac-launchd.sh reload
#   scripts/install-mac-launchd.sh uninstall
#   scripts/install-mac-launchd.sh status
#   scripts/install-mac-launchd.sh run-now
#
# TCC 주의: macOS는 launchd agent가 ~/Documents 안의 스크립트를 직접
# 실행하는 것을 차단한다 (Operation not permitted). 이 스크립트는 entry
# point를 ~/.local/bin/ 아래에 inline으로 생성해 우회한다.

set -Eeuo pipefail

LABEL="com.hotinbeauty.crawl"
PROJECT_PATH="$(cd "$(dirname "$0")/.." && pwd)"
ENTRY="$HOME/.local/bin/hotinbeauty-crawl"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs/hotinbeauty"

ensure_log_dir() { mkdir -p "$LOG_DIR"; }

render_entry() {
  ensure_log_dir
  mkdir -p "$(dirname "$ENTRY")"
  cat > "$ENTRY" <<SH
#!/usr/bin/env bash
# Generated by scripts/install-mac-launchd.sh — do not edit manually.
# launchd entry — lives outside ~/Documents to bypass macOS TCC.

set -Eeuo pipefail

LOG="$LOG_DIR/crawl-\$(date +%Y-%m-%d).log"
mkdir -p "$LOG_DIR"
exec >> "\$LOG" 2>&1
trap 'EXIT_CODE=\$?; echo "=== \$(date '\''+%Y-%m-%d %H:%M:%S %Z'\'') crawl end (exit=\$EXIT_CODE) ==="' EXIT

echo ""
echo "=== \$(date '+%Y-%m-%d %H:%M:%S %Z') crawl start (via launchd) ==="

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$PATH"
if [ -s "\$HOME/.nvm/nvm.sh" ]; then . "\$HOME/.nvm/nvm.sh"; fi

cd "$PROJECT_PATH"

echo "node=\$(node -v) npm=\$(npm -v) pwd=\$(pwd)"
bash scripts/run-scheduled-crawls.sh
SH
  chmod +x "$ENTRY"
  echo "entry -> $ENTRY (points at $PROJECT_PATH)"
}

render_plist() {
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$ENTRY</string>
  </array>
  <key>WorkingDirectory</key><string>$HOME</string>
  <key>StartCalendarInterval</key>
  <array>
    <dict><key>Hour</key><integer>6</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>9</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>10</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>11</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>12</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>13</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>14</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>15</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>16</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>17</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>18</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>19</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>20</integer><key>Minute</key><integer>0</integer></dict>
    <dict><key>Hour</key><integer>21</integer><key>Minute</key><integer>0</integer></dict>
  </array>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>$LOG_DIR/launchd.out.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/launchd.err.log</string>
  <key>ProcessType</key><string>Background</string>
</dict>
</plist>
EOF
  echo "plist -> $PLIST"
}

case "${1:-}" in
  install|reload)
    render_entry
    render_plist
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load -w "$PLIST"
    launchctl list "$LABEL" >/dev/null && echo "$1 complete: $LABEL"
    ;;
  uninstall)
    launchctl unload "$PLIST" 2>/dev/null || true
    rm -f "$PLIST" "$ENTRY"
    echo "uninstalled: $LABEL"
    ;;
  status)
    launchctl list "$LABEL" 2>&1 || echo "not loaded"
    echo "--- recent log ---"
    tail -n 60 "$LOG_DIR/crawl-$(date +%Y-%m-%d).log" 2>/dev/null || echo "(no log today)"
    ;;
  run-now)
    launchctl kickstart -k "gui/$(id -u)/$LABEL"
    echo "triggered. tail -f $LOG_DIR/crawl-$(date +%Y-%m-%d).log"
    ;;
  *)
    echo "usage: $0 {install|reload|uninstall|status|run-now}"; exit 1 ;;
esac
