#!/usr/bin/env bash
# hotinbeauty — 화해(hwahae) 크롤 스케줄 (launchd) 설치/재로드/해제.
# usage:
#   scripts/install-hwahae-launchd.sh install
#   scripts/install-hwahae-launchd.sh reload
#   scripts/install-hwahae-launchd.sh uninstall
#   scripts/install-hwahae-launchd.sh status
#   scripts/install-hwahae-launchd.sh run-now
#
# TCC 주의: macOS 는 launchd agent 가 ~/Documents 안 스크립트를 직접
# 실행하는 것을 차단한다 (Operation not permitted). 이 스크립트는 entry
# point 를 ~/.local/bin/ 아래에 inline 으로 생성해 우회한다.
#
# 올영 크롤(com.hotinbeauty.crawl, 09:00+21:00) 과 충돌하지 않도록
# label/entry/log 를 별도로 유지한다.

set -Eeuo pipefail

LABEL="com.hotinbeauty.hwahae-crawl"
PROJECT_PATH="$(cd "$(dirname "$0")/.." && pwd)"
ENTRY="$HOME/.local/bin/hotinbeauty-hwahae-crawl"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs/hotinbeauty"

ensure_log_dir() { mkdir -p "$LOG_DIR"; }

render_entry() {
  ensure_log_dir
  mkdir -p "$(dirname "$ENTRY")"
  cat > "$ENTRY" <<SH
#!/usr/bin/env bash
# Generated by scripts/install-hwahae-launchd.sh — do not edit manually.
# launchd entry — lives outside ~/Documents to bypass macOS TCC.

set -Eeuo pipefail

LOG="$LOG_DIR/hwahae-\$(date +%Y-%m-%d).log"
mkdir -p "$LOG_DIR"
exec >> "\$LOG" 2>&1

echo ""
echo "=== \$(date '+%Y-%m-%d %H:%M:%S %Z') hwahae crawl start (via launchd) ==="

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$PATH"
if [ -s "\$HOME/.nvm/nvm.sh" ]; then . "\$HOME/.nvm/nvm.sh"; fi

cd "$PROJECT_PATH"

echo "node=\$(node -v) npm=\$(npm -v) pwd=\$(pwd)"
npm run crawl:hwahae
echo "=== \$(date '+%Y-%m-%d %H:%M:%S %Z') hwahae crawl end (exit=\$?) ==="
SH
  chmod +x "$ENTRY"
  echo "entry -> $ENTRY (points at $PROJECT_PATH)"
}

render_plist() {
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$ENTRY</string>
  </array>
  <key>WorkingDirectory</key><string>$HOME</string>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>6</integer>
    <key>Minute</key><integer>0</integer>
  </dict>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>$LOG_DIR/hwahae-launchd.out.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/hwahae-launchd.err.log</string>
  <key>ProcessType</key><string>Background</string>
</dict>
</plist>
EOF
  echo "plist -> $PLIST"
}

case "${1:-}" in
  install|reload)
    render_entry
    render_plist
    launchctl unload "$PLIST" 2>/dev/null || true
    launchctl load -w "$PLIST"
    launchctl list "$LABEL" >/dev/null && echo "$1 complete: $LABEL"
    ;;
  uninstall)
    launchctl unload "$PLIST" 2>/dev/null || true
    rm -f "$PLIST" "$ENTRY"
    echo "uninstalled: $LABEL"
    ;;
  status)
    launchctl list "$LABEL" 2>&1 || echo "not loaded"
    echo "--- recent log ($(date +%Y-%m-%d)) ---"
    tail -n 60 "$LOG_DIR/hwahae-$(date +%Y-%m-%d).log" 2>/dev/null || echo "(no log today)"
    ;;
  run-now)
    launchctl kickstart -k "gui/$(id -u)/$LABEL"
    echo "triggered. tail -f $LOG_DIR/hwahae-$(date +%Y-%m-%d).log"
    ;;
  *)
    echo "usage: $0 {install|reload|uninstall|status|run-now}"; exit 1 ;;
esac
